Homework1 - types and operators
viktoriya-job/TMS_AT pull request #1
Opened 2023-11-17 17:28 UTC by viktoriya-job

Добрый день. Не стала оставлять в ветке homeWork код, прописываемый на лекции - пока не поняла, критично ли это

2023-11-19 21:08 UTC, wildpioneer requested changes

2023-11-19 21:08 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            Console.Write("Введите первое число:\t\t");
Почему в этой строке выводится два знака табуляции
А в следующей (строка 41) всего один?

2023-11-19 21:08 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +                    Console.Write($"Результат:\t\t\t{num1}{operat}{num2}=");
Каким образом формируется количества знаков табуляции?

2023-11-19 21:08 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +                    Console.WriteLine($"Ошибка: Попытка деления на 0");
Знак интерполяции не нужен - потому что ты выводишь просто текст

2023-11-19 21:08 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            if (num / 2 * 2 == num)
Хитро - но не совсем правильно. Но мысль интересная.

2023-11-19 21:12 UTC, viktoriya-job commented on TypesAndOperators/Program.cs
> +                    Console.Write($"Результат:\t\t\t{num1}{operat}{num2}=");
Зависит  от длины выводимой пользователю строки - табы проставлены так, чтобы в итоге введенные значения отображались в столбик

2023-11-19 21:12 UTC, viktoriya-job commented on TypesAndOperators/Program.cs
> +                    Console.WriteLine($"Ошибка: Попытка деления на 0");
Разогналась, согласна)

2023-11-20 06:03 UTC, viktoriya-job commented on TypesAndOperators/Program.cs
> +            if (num / 2 * 2 == num)
Добавила еще один алгоритм - определяем, что последняя цифра числа делится на два, сверяя ее с пятью четными цифрами. Не уверена, что имелось ввиду такое решение, но других мыслей пока нет (и эту идею подсмотрела у Жени, если честно=))

2023-11-21 05:57 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            if (num / 2 * 2 == num)
Пойдет ;)

2023-11-23 17:49 UTC, viktoriya-job commented on TypesAndOperators/Program.cs
> +            Console.Write("Введите первое число:\t\t");
Заменила табы на необработанные строковые литералы)

2023-11-26 18:05 UTC, wildpioneer requested changes

2023-11-26 18:05 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +        if (func > 5)
1. Перед IF обычно делают пуствю строку
2. А если я введу -1 - будет работать?

2023-11-26 18:05 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +                default: Console.WriteLine("Непредвиденная ошибка"); break;
А в чем ошибка? И почему она непредвиденная?

2023-11-27 14:48 UTC, viktoriya-job commented on TypesAndOperators/Program.cs
> +        if (func > 5)
1. Спасибо, поправила, учту
2. Нет, это баг) 
Пофиксила - теперь берем модуль числа и работаем далее с ним

2023-11-27 15:00 UTC, viktoriya-job commented on TypesAndOperators/Program.cs
> +                default: Console.WriteLine("Непредвиденная ошибка"); break;
Избыточный кейс. мы в него не попадем. При вводе не целого неотрицательного числа будет эксепшн, который пока не научилась обрабатывать; остальные случаи покрыты условными операторами: [0,5] switch и (5, ∞) if. Убрала избыточные проверки

2023-12-28 11:16 UTC, wildpioneer commented
Проверено

2023-12-28 11:16 UTC, closed without merging