Homework NUnit
viktoriya-job/TMS_AT pull request #12
Opened 2024-01-27 18:58 UTC by viktoriya-job

2024-01-29 09:51 UTC, wildpioneer requested changes

2024-01-29 09:51 UTC, wildpioneer commented on NUnitTest/Calc.cs
> +        if (b == 0)
Хитришь - а на самом деле для double не так ;) - хочу видеть double.NaN

2024-01-29 09:51 UTC, wildpioneer commented on NUnitTest/CalcTests.cs
> +        [SetUp]
По факту можно и так - но все же, зачем нам этот класс инициализировать каждый раз перед каждым тестом? Достаточно одного раза - а это OneTimeSetup

2024-01-29 09:51 UTC, wildpioneer commented on NUnitTest/CalcTests.cs
> +        public void CalcTestWhenDoubleDivThenCorrectValueReturned2(double x, double y, double result)
Хочу видеть еще тесты на Repeat, Retry и оставшиеся не использованные атрибуты

2024-02-03 08:54 UTC, viktoriya-job commented on NUnitTest/CalcTests.cs
> +        [SetUp]
Поправила

2024-02-03 09:37 UTC, viktoriya-job commented on NUnitTest/CalcTests.cs
> +        public void CalcTestWhenDoubleDivThenCorrectValueReturned2(double x, double y, double result)
Добавила

2024-02-03 09:42 UTC, viktoriya-job commented on NUnitTest/Calc.cs
> +        if (b == 0)
проверка работает с double.IsInfinity - не удалось сделать с double.NaN

2024-02-05 17:32 UTC, wildpioneer commented on NUnitTest/Calc.cs
> +        if (b == 0)
double result = 0.0 / 0.0;
Assert.IsTrue(double.IsNaN(result));

2024-02-05 17:32 UTC, wildpioneer commented
Проверено

2024-02-05 17:32 UTC, closed without merging