homework SeleniumBasic
viktoriya-job/TMS_AT pull request #13
Opened 2024-01-28 20:19 UTC by viktoriya-job

2024-01-29 09:55 UTC, wildpioneer requested changes

2024-01-29 09:55 UTC, wildpioneer commented on SeleniumBasic/Tests/FirstTest.cs
> +            Driver.SwitchTo().Frame(0);
Тут у меня затык - но это не критично.
Должно быть:
Thread.Sleep(2000);
Driver.SwitchTo().Frame(1);

2024-01-29 09:55 UTC, wildpioneer commented on SeleniumBasic/Tests/LaminateTest.cs
> +            Assert.That(result.Text, Is.EqualTo("Требуемое количество плашек ламината: 65\r\nКоличество упаковок ламината: 4\r\nСтоимость ламината: 0 руб\r\nВес ламината: 0 кг"));
<img width="2398" alt="image" src="https://github.com/viktoriya-job/TMS_AT/assets/8968693/028b5f93-2896-48e5-a34b-8d938eaf0b09">

2024-01-29 10:12 UTC, viktoriya-job commented on SeleniumBasic/Tests/FirstTest.cs
> +            Driver.SwitchTo().Frame(0);
У меня реклама не всплывает - то есть Sleep оказался не нужен. И с Frame(1) категорически не ищется фрейм) 
с Frame(0) ищется

2024-01-29 10:13 UTC, viktoriya-job commented on SeleniumBasic/Tests/LaminateTest.cs
> +            Assert.That(result.Text, Is.EqualTo("Требуемое количество плашек ламината: 65\r\nКоличество упаковок ламината: 4\r\nСтоимость ламината: 0 руб\r\nВес ламината: 0 кг"));
Как так-то

2024-01-29 10:17 UTC, viktoriya-job commented on SeleniumBasic/Tests/LaminateTest.cs
> +            Assert.That(result.Text, Is.EqualTo("Требуемое количество плашек ламината: 65\r\nКоличество упаковок ламината: 4\r\nСтоимость ламината: 0 руб\r\nВес ламината: 0 кг"));
![изображение](https://github.com/viktoriya-job/TMS_AT/assets/150160365/f270460c-21c3-4e1f-873a-659434ad0c70)

2024-01-29 10:19 UTC, viktoriya-job commented on SeleniumBasic/Tests/LaminateTest.cs
> +            Assert.That(result.Text, Is.EqualTo("Требуемое количество плашек ламината: 65\r\nКоличество упаковок ламината: 4\r\nСтоимость ламината: 0 руб\r\nВес ламината: 0 кг"));
Ну а если оставить только \n, наоборот. ошибка:
![изображение](https://github.com/viktoriya-job/TMS_AT/assets/150160365/cb339af1-d120-4539-9c46-a06341f8b80a)

2024-01-29 10:23 UTC, viktoriya-job commented on SeleniumBasic/Tests/FirstTest.cs
> +            Driver.SwitchTo().Frame(0);
![изображение](https://github.com/viktoriya-job/TMS_AT/assets/150160365/a5ccde27-a22d-4660-816d-e16730a4f8f9)

2024-02-03 07:08 UTC, viktoriya-job commented on SeleniumBasic/Tests/FirstTest.cs
> +            Driver.SwitchTo().Frame(0);
Изменила поиск фрейма 
 Driver.SwitchTo().Frame(Driver.FindElement(By.CssSelector("[src='/scripts/gfr/?v=1']")))

2024-02-05 17:35 UTC, wildpioneer requested changes

2024-02-05 17:35 UTC, wildpioneer commented on SeleniumBasic/Tests/LaminateTest.cs
> +            Assert.That(result.Text, Is.EqualTo("Требуемое количество плашек ламината: 65\r\nКоличество упаковок ламината: 4\r\nСтоимость ламината: 0 руб\r\nВес ламината: 0 кг"));
Не - эти скрины должны навести тебя на мысль - что в разных браузерах или системах можгут быть разные скрытые символы - и можно от это избавиться - заменив их на пустые символы ;)

2024-02-09 05:17 UTC, viktoriya-job commented on SeleniumBasic/Tests/LaminateTest.cs
> +            Assert.That(result.Text, Is.EqualTo("Требуемое количество плашек ламината: 65\r\nКоличество упаковок ламината: 4\r\nСтоимость ламината: 0 руб\r\nВес ламината: 0 кг"));
Ой-ёй... )) Да, символ переноса каретки можно было ожидать. Поправила, спасибо

Добавила ввод значений в два последних поля - не было умысла схитрить) Предпоследнее поле было скрыто, и я его не видела, а последнее ведет себя странно - любое введенное значение меняется на 8, и я поначалу решила оставить его введенным по-умолчанию.  Сейчас затираю, и снова ввожу 8

2024-02-12 21:01 UTC, wildpioneer commented
Проверено

2024-02-12 21:01 UTC, closed without merging