Homework selenium advanced
viktoriya-job/TMS_AT pull request #15
Opened 2024-02-08 16:13 UTC by viktoriya-job

2024-02-12 21:00 UTC, wildpioneer requested changes

2024-02-12 21:00 UTC, wildpioneer commented on SeleniumBasic/Helpers/WaitsHelper.cs
> +            while (true)
Ну как вариант своего ожидания - отлично, но почему не использовать варианты как мы это делали через _wait.Until();

2024-02-26 16:50 UTC, viktoriya-job commented on SeleniumBasic/Helpers/WaitsHelper.cs
> +            while (true)
Дописала WaitFileForExist1)

        public bool WaitFileForExist1(string path)
        {
            return _wait.Until(_ => File.Exists(path));
        }

2024-03-19 11:42 UTC, wildpioneer commented
Проверено

2024-03-19 11:42 UTC, closed without merging