Homework page object steps
viktoriya-job/TMS_AT pull request #16
Opened 2024-02-17 20:15 UTC by viktoriya-job

2024-02-25 21:08 UTC, wildpioneer requested changes

2024-02-25 21:08 UTC, wildpioneer commented on PageObjectSteps_SauceDemo/Pages/CheckoutStepOnePage.cs
> +        protected override string GetEndpoint() => _endPoint;
Форматирование - пустая строка перед методом

2024-02-25 21:08 UTC, wildpioneer commented on PageObjectSteps_SauceDemo/Pages/CheckoutStepTwoPage.cs
> +        protected override string GetEndpoint() => _endPoint;
Форматирование - пустая строка перед методом

2024-02-25 21:08 UTC, wildpioneer commented on PageObjectSteps_SauceDemo/Pages/FinishPage.cs
> +        protected override string GetEndpoint() => _endPoint;
Форматирование - пустая строка перед методом

2024-02-25 21:08 UTC, wildpioneer commented on PageObjectSteps_SauceDemo/Pages/InventoryPage.cs
> +            ItemsSmall = new List<ItemSmall>();
Что-то не понимаю - что это за механизм???  Мы такое делаем только в обертках.

2024-02-25 21:08 UTC, wildpioneer commented on PageObjectSteps_SauceDemo/Pages/InventoryPage.cs
> +        protected override string GetEndpoint() => _endPoint;
Форматирование - пустая строка перед методом

2024-02-26 16:14 UTC, viktoriya-job commented on PageObjectSteps_SauceDemo/Pages/CheckoutStepOnePage.cs
> +        protected override string GetEndpoint() => _endPoint;
Fixed

2024-02-26 16:15 UTC, viktoriya-job commented on PageObjectSteps_SauceDemo/Pages/CheckoutStepTwoPage.cs
> +        protected override string GetEndpoint() => _endPoint;
Fixed

2024-02-26 16:15 UTC, viktoriya-job commented on PageObjectSteps_SauceDemo/Pages/FinishPage.cs
> +        protected override string GetEndpoint() => _endPoint;
Fixed

2024-02-26 16:18 UTC, viktoriya-job commented on PageObjectSteps_SauceDemo/Pages/InventoryPage.cs
> +            ItemsSmall = new List<ItemSmall>();
Сначала описала каждую карточку как отдельную страницу, но не была уверена, что это правильно и сделала единый класс для описания всех карточек =\

Эх, было желание вообще все переделать) Теперь и повод есть)

2024-02-26 16:21 UTC, viktoriya-job commented on PageObjectSteps_SauceDemo/Pages/InventoryPage.cs
> +        protected override string GetEndpoint() => _endPoint;
Fixed

2024-03-02 08:41 UTC, viktoriya-job commented on PageObjectSteps_SauceDemo/Pages/InventoryPage.cs
> +            ItemsSmall = new List<ItemSmall>();
Переписала

2024-03-02 08:41 UTC, viktoriya-job commented
Проверьте, пожалуйста, Allure в этом же PullRequest

2024-03-19 11:42 UTC, wildpioneer commented
Провервено

2024-03-19 11:42 UTC, closed without merging