Home work -Arrays
viktoriya-job/TMS_AT pull request #2
Opened 2023-11-19 17:40 UTC by viktoriya-job

2023-11-26 20:35 UTC, wildpioneer requested changes

2023-11-26 20:35 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            if (task == 0 || task > 12)
Что будет если я введу -1?

2023-11-26 20:35 UTC, wildpioneer commented on TypesAndOperators/Task2.cs
> +            if (Array.Exists(array, el => el == num) == false)
Если метод возвращает true или false - то зачем проверять равенство true или false в IF - правило точно такое же как и для переменных - не надо

2023-11-26 20:35 UTC, wildpioneer commented on TypesAndOperators/Task2.cs
> +                array[i] = random.Next(100);
Рандоме от 100 редко будет вхождение одинаковых чисел в массив - потому надо до 30 - будет получше - но это  не критично

2023-11-26 20:35 UTC, wildpioneer commented on TypesAndOperators/Task2.cs
> +                byte lengthArray = Convert.ToByte(array.GetLength(0));
Мы уже научились конвертировать - так что теперь можно не использовать это везде
Лучше использовать int

2023-11-26 20:35 UTC, wildpioneer commented on TypesAndOperators/Task2.cs
> +                }
Весьма интересное решение - по факту ты не удаляешь элемент - а перемещаешь его в конец. Что является не точным решением

2023-11-26 20:35 UTC, wildpioneer commented on TypesAndOperators/Task3.cs
> +            Array.Sort(array);
Вроде по условию не надо было сортировать

2023-11-26 20:35 UTC, wildpioneer commented on TypesAndOperators/Task3.cs
> +            Console.WriteLine($"Average\t: {array[array.GetLength(0) / 2]}");
Опять не совсем стандартное решение - но почему бы и нет.

2023-11-26 20:35 UTC, wildpioneer commented on TypesAndOperators/Task8.cs
> +            while (lengthArray > 0)
Опять же странный вариант пузырька
Обычно число как бы всплывает от конца массива в начало - а у тебя наоборот.

2023-11-27 15:02 UTC, viktoriya-job commented on TypesAndOperators/Program.cs
> +            if (task == 0 || task > 12)
тип данных вводимого числа- byte, поэтому будет эксепшн, пока не научусь обрабатывать их

2023-11-27 18:38 UTC, viktoriya-job commented on TypesAndOperators/Task2.cs
> +                array[i] = random.Next(100);
Тестировала, конечно, на маленьких диапазонах вплоть до единственного числа во всем массиве) Поставила 30, все-равно было что коммитить.

2023-11-27 18:39 UTC, viktoriya-job commented on TypesAndOperators/Task2.cs
> +            if (Array.Exists(array, el => el == num) == false)
Спасибо, учту. Исправила

2023-11-27 18:39 UTC, viktoriya-job commented on TypesAndOperators/Task2.cs
> +                }
Добавила метод RemoveSomeArrayElements2 с другим алгоритмом

2023-11-27 19:07 UTC, viktoriya-job commented on TypesAndOperators/Program.cs
> +            if (task == 0 || task > 12)
Добавила try-catch - пока только для ввода номера задачи в Program

2023-11-27 19:09 UTC, viktoriya-job commented on TypesAndOperators/Task3.cs
> +            Array.Sort(array);
Мне этот вариант показался наиболее простым для получения трех искомых величин - отсортировать массив перед получением макс, мин и среднего. Вывод отсортированного массива пользователю - только для упрощения визуальной проверки корректности работы задачи

2023-11-28 05:17 UTC, viktoriya-job commented on TypesAndOperators/Task8.cs
> +            while (lengthArray > 0)
Добавила метод BubbleSort2, в котором сортировка идет от конца в начало

Изначально ориентировалась на алгоритм пузырька из вики https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0_%D0%BF%D1%83%D0%B7%D1%8B%D1%80%D1%8C%D0%BA%D0%BE%D0%BC
"... При каждом проходе алгоритма по внутреннему циклу очередной наибольший элемент массива ставится на своё место в конце массива рядом с предыдущим «наибольшим элементом», а наименьший элемент перемещается на одну позицию к началу массива (как бы «всплывает» до нужной позиции, как пузырёк в воде — откуда и название алгоритма)"

2023-12-28 11:17 UTC, wildpioneer commented on TypesAndOperators/Program.cs
> +            if (task == 0 || task > 12)
Верно

2023-12-28 11:18 UTC, wildpioneer commented
Проверено

2023-12-28 11:18 UTC, closed without merging