Home work strings
viktoriya-job/TMS_AT pull request #3
Opened 2023-11-25 18:52 UTC by viktoriya-job

2023-11-26 21:05 UTC, wildpioneer requested changes

2023-11-26 21:05 UTC, wildpioneer commented on StringApp/bin/Debug/net7.0/Files/InputData_task1.txt
> +123 test1 12test34 test323test testABC
Это немного не так делается - но потом расскажу - молодец что сделала так

2023-11-26 21:05 UTC, wildpioneer commented on StringApp/Task1.cs
> +        public static string ReplaceSomesubstringAndRemoveAllDigits(string inputString, string replacementSubstring, string targetSubstring)
Substring должно тоже быть с большой буквы

2023-11-26 21:05 UTC, wildpioneer commented on StringApp/Task1.cs
> +                    i--; // при удалении элемента пропускаем символ - вернем счетчик, иначе не обработаются идущие подряд символы
Так делать нельзя - нужно менять тип цикла
Изменение индекса цикла FOR может привести к ошибкам

2023-11-26 21:05 UTC, wildpioneer commented on StringApp/Task3.cs
> +        public static void SplitString(string inputString,string separator)
пробел между параметрами

2023-11-26 21:05 UTC, wildpioneer commented on StringApp/Task3.cs
> +                foreach (string str in newStrings)
Пустая строка перед foreach

2023-11-26 21:05 UTC, wildpioneer commented on StringApp/Task4.cs
> +                //код можно сделать более читабельным, введя переменные
если можно сделать более читаемым - значит надо сделать

2023-11-26 21:05 UTC, wildpioneer commented on StringApp/Task4.cs
> +        public static string ReplaceWordInString(string inputString, string substringToRemove, string substringToInsert1, string substringToInsert2, string? replacementLastPart)
А почему только replacementLastPart может быть null??

2023-11-26 21:05 UTC, wildpioneer commented on StringApp/Task5.cs
> +
Тут пустая строка ненужна

2023-11-26 21:05 UTC, wildpioneer commented on StringApp/Task5.cs
> +                if (matchCollect.Count > 0) //излишне, но оставила для себя - не забыть о полезной конструкции
А здесь нужна

2023-11-28 17:46 UTC, viktoriya-job commented on StringApp/Task1.cs
> +        public static string ReplaceSomesubstringAndRemoveAllDigits(string inputString, string replacementSubstring, string targetSubstring)
Спасибо, поправила

2023-11-28 17:47 UTC, viktoriya-job commented on StringApp/Task3.cs
> +        public static void SplitString(string inputString,string separator)
Учла, спасибо)

2023-11-28 17:47 UTC, viktoriya-job commented on StringApp/Task3.cs
> +                foreach (string str in newStrings)
Учла

2023-11-28 17:47 UTC, viktoriya-job commented on StringApp/Task5.cs
> +
Учла

2023-11-28 17:47 UTC, viktoriya-job commented on StringApp/Task5.cs
> +                if (matchCollect.Count > 0) //излишне, но оставила для себя - не забыть о полезной конструкции
Учла

2023-11-28 17:54 UTC, viktoriya-job commented on StringApp/Task1.cs
> +                    i--; // при удалении элемента пропускаем символ - вернем счетчик, иначе не обработаются идущие подряд символы
Пофиксила

2023-11-29 06:56 UTC, viktoriya-job commented on StringApp/Task4.cs
> +        public static string ReplaceWordInString(string inputString, string substringToRemove, string substringToInsert1, string substringToInsert2, string? replacementLastPart)
Начала и не довела до ума, самой смотреть страшно
Переписала метод для Task4: RemoveAndInsertSomeSubstrings с пятью параметрами

2023-11-29 06:58 UTC, viktoriya-job commented on StringApp/Task4.cs
> +                //код можно сделать более читабельным, введя переменные
fixed

2023-11-29 17:37 UTC, viktoriya-job commented on StringApp/bin/Debug/net7.0/Files/InputData_task1.txt
> +123 test1 12test34 test323test testABC
Спасибо!

2023-12-28 11:20 UTC, wildpioneer commented
Проверено

2023-12-28 11:20 UTC, closed without merging